# Generated by Django 4.0.2 on 2022-04-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='ads', max_length=128),
            preserve_default=False,
        ),
    ]
