# Generated by Django 4.0.2 on 2022-05-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorId',
            field=models.DecimalField(decimal_places=0, default=6, max_digits=20),
            preserve_default=False,
        ),
    ]
